class Surah {
  final int number;
  final String name;
  final String englishName;
  final String revelationType;
  final int versesCount;

  const Surah({
    required this.number,
    required this.name,
    required this.englishName,
    required this.revelationType,
    required this.versesCount,
  });
}

const List<Surah> quranSurahs = [
  Surah(number: 1, name: "الفاتحة", englishName: "Al-Fatiha", revelationType: "Meccan", versesCount: 7),
  Surah(number: 2, name: "البقرة", englishName: "Al-Baqara", revelationType: "Medinan", versesCount: 286),
  Surah(number: 3, name: "آل عمران", englishName: "Aal-Imran", revelationType: "Medinan", versesCount: 200),
  Surah(number: 4, name: "النساء", englishName: "An-Nisaa'", revelationType: "Medinan", versesCount: 176),
  Surah(number: 5, name: "المائدة", englishName: "Al-Ma'ida", revelationType: "Medinan", versesCount: 120),
  Surah(number: 6, name: "الأنعام", englishName: "Al-An'am", revelationType: "Meccan", versesCount: 165),
  Surah(number: 7, name: "الأعراف", englishName: "Al-A'raf", revelationType: "Meccan", versesCount: 206),
  Surah(number: 8, name: "الأنفال", englishName: "Al-Anfal", revelationType: "Medinan", versesCount: 75),
  Surah(number: 9, name: "التوبة", englishName: "Al-Tawba", revelationType: "Medinan", versesCount: 129),
  Surah(number: 10, name: "يونس", englishName: "Yunus", revelationType: "Meccan", versesCount: 109),
  Surah(number: 11, name: "هود", englishName: "Hud", revelationType: "Meccan", versesCount: 123),
  Surah(number: 12, name: "يوسف", englishName: "Yusuf", revelationType: "Meccan", versesCount: 111),
  Surah(number: 13, name: "الرعد", englishName: "Ar-Ra'd", revelationType: "Medinan", versesCount: 43),
  Surah(number: 14, name: "إبراهيم", englishName: "Ibrahim", revelationType: "Meccan", versesCount: 52),
  Surah(number: 15, name: "الحجر", englishName: "Al-Hijr", revelationType: "Meccan", versesCount: 99),
  Surah(number: 16, name: "النحل", englishName: "An-Nahl", revelationType: "Meccan", versesCount: 128),
  Surah(number: 17, name: "الإسراء", englishName: "Al-Israa", revelationType: "Meccan", versesCount: 111),
  Surah(number: 18, name: "الكهف", englishName: "Al-Kahf", revelationType: "Meccan", versesCount: 110),
  Surah(number: 19, name: "مريم", englishName: "Maryam", revelationType: "Meccan", versesCount: 98),
  Surah(number: 20, name: "طه", englishName: "Ta-Ha", revelationType: "Meccan", versesCount: 135),
  Surah(number: 21, name: "الأنبياء", englishName: "Al-Anbiya", revelationType: "Meccan", versesCount: 112),
  Surah(number: 22, name: "الحج", englishName: "Al-Hajj", revelationType: "Medinan", versesCount: 78),
  Surah(number: 23, name: "المؤمنون", englishName: "Al-Muminun", revelationType: "Meccan", versesCount: 118),
  Surah(number: 24, name: "النور", englishName: "An-Nur", revelationType: "Medinan", versesCount: 64),
  Surah(number: 25, name: "الفرقان", englishName: "Al-Furqan", revelationType: "Meccan", versesCount: 77),
  Surah(number: 26, name: "الشعراء", englishName: "Ash-Shuara", revelationType: "Meccan", versesCount: 227),
  Surah(number: 27, name: "النمل", englishName: "An-Naml", revelationType: "Meccan", versesCount: 93),
  Surah(number: 28, name: "القصص", englishName: "Al-Qasas", revelationType: "Meccan", versesCount: 88),
  Surah(number: 29, name: "العنكبوت", englishName: "Al-Ankabut", revelationType: "Meccan", versesCount: 69),
  Surah(number: 30, name: "الروم", englishName: "Ar-Rum", revelationType: "Meccan", versesCount: 60),
  Surah(number: 31, name: "لقمان", englishName: "Luqman", revelationType: "Meccan", versesCount: 34),
  Surah(number: 32, name: "السجدة", englishName: "As-Sajdah", revelationType: "Meccan", versesCount: 30),
  Surah(number: 33, name: "الأحزاب", englishName: "Al-Ahzab", revelationType: "Medinan", versesCount: 73),
  Surah(number: 34, name: "سبأ", englishName: "Saba", revelationType: "Meccan", versesCount: 54),
  Surah(number: 35, name: "فاطر", englishName: "Fatir", revelationType: "Meccan", versesCount: 45),
  Surah(number: 36, name: "يس", englishName: "Yasin", revelationType: "Meccan", versesCount: 83),
  Surah(number: 37, name: "الصافات", englishName: "As-Saffat", revelationType: "Meccan", versesCount: 182),
  Surah(number: 38, name: "ص", englishName: "Sad", revelationType: "Meccan", versesCount: 88),
  Surah(number: 39, name: "الزمر", englishName: "Az-Zumar", revelationType: "Meccan", versesCount: 75),
  Surah(number: 40, name: "غافر", englishName: "Ghafir", revelationType: "Meccan", versesCount: 85),
  Surah(number: 41, name: "فصلت", englishName: "Fussilat", revelationType: "Meccan", versesCount: 54),
  Surah(number: 42, name: "الشورى", englishName: "Ash-Shura", revelationType: "Meccan", versesCount: 53),
  Surah(number: 43, name: "الزخرف", englishName: "Az-Zukhruf", revelationType: "Meccan", versesCount: 89),
  Surah(number: 44, name: "الدخان", englishName: "Ad-Dukhan", revelationType: "Meccan", versesCount: 59),
  Surah(number: 45, name: "الجاثية", englishName: "Al-Jathiya", revelationType: "Meccan", versesCount: 37),
  Surah(number: 46, name: "الأحقاف", englishName: "Al-Ahqaf", revelationType: "Meccan", versesCount: 35),
  Surah(number: 47, name: "محمد", englishName: "Muhammad", revelationType: "Medinan", versesCount: 38),
  Surah(number: 48, name: "الفتح", englishName: "Al-Fath", revelationType: "Medinan", versesCount: 29),
  Surah(number: 49, name: "الحجرات", englishName: "Al-Hujurat", revelationType: "Medinan", versesCount: 18),
  Surah(number: 50, name: "ق", englishName: "Qaf", revelationType: "Meccan", versesCount: 45),
  Surah(number: 51, name: "الذاريات", englishName: "Az-Zariyat", revelationType: "Meccan", versesCount: 60),
  Surah(number: 52, name: "الطور", englishName: "At-Tur", revelationType: "Meccan", versesCount: 49),
  Surah(number: 53, name: "النجم", englishName: "An-Najm", revelationType: "Meccan", versesCount: 62),
  Surah(number: 54, name: "القمر", englishName: "Al-Qamar", revelationType: "Meccan", versesCount: 55),
  Surah(number: 55, name: "الرحمن", englishName: "Ar-Rahman", revelationType: "Medinan", versesCount: 78),
  Surah(number: 56, name: "الواقعة", englishName: "Al-Waqia", revelationType: "Meccan", versesCount: 96),
  Surah(number: 57, name: "الحديد", englishName: "Al-Hadid", revelationType: "Medinan", versesCount: 29),
  Surah(number: 58, name: "المجادلة", englishName: "Al-Mujadilah", revelationType: "Medinan", versesCount: 22),
  Surah(number: 59, name: "الحشر", englishName: "Al-Hashr", revelationType: "Medinan", versesCount: 24),
  Surah(number: 60, name: "الممتحنة", englishName: "Al-Mumtahinah", revelationType: "Medinan", versesCount: 13),
  Surah(number: 61, name: "الصف", englishName: "As-Saff", revelationType: "Medinan", versesCount: 14),
  Surah(number: 62, name: "الجمعة", englishName: "Al-Jumu'ah", revelationType: "Medinan", versesCount: 11),
  Surah(number: 63, name: "المنافقون", englishName: "Al-Munafiqun", revelationType: "Medinan", versesCount: 11),
  Surah(number: 64, name: "التغابن", englishName: "At-Taghabun", revelationType: "Medinan", versesCount: 18),
  Surah(number: 65, name: "الطلاق", englishName: "At-Talaq", revelationType: "Medinan", versesCount: 12),
  Surah(number: 66, name: "التحريم", englishName: "At-Tahrim", revelationType: "Medinan", versesCount: 12),
  Surah(number: 67, name: "الملك", englishName: "Al-Mulk", revelationType: "Meccan", versesCount: 30),
  Surah(number: 68, name: "القلم", englishName: "Al-Qalam", revelationType: "Meccan", versesCount: 52),
  Surah(number: 69, name: "الحاقة", englishName: "Al-Haqqah", revelationType: "Meccan", versesCount: 52),
  Surah(number: 70, name: "المعارج", englishName: "Al-Ma'arij", revelationType: "Meccan", versesCount: 44),
  Surah(number: 71, name: "نوح", englishName: "Nuh", revelationType: "Meccan", versesCount: 28),
  Surah(number: 72, name: "الجن", englishName: "Al-Jinn", revelationType: "Meccan", versesCount: 28),
  Surah(number: 73, name: "المزمل", englishName: "Al-Muzzammil", revelationType: "Meccan", versesCount: 20),
  Surah(number: 74, name: "المدثر", englishName: "Al-Muddaththir", revelationType: "Meccan", versesCount: 56),
  Surah(number: 75, name: "القيامة", englishName: "Al-Qiyamah", revelationType: "Meccan", versesCount: 40),
  Surah(number: 76, name: "الإنسان", englishName: "Al-Insan", revelationType: "Medinan", versesCount: 31),
  Surah(number: 77, name: "المرسلات", englishName: "Al-Mursalat", revelationType: "Meccan", versesCount: 50),
  Surah(number: 78, name: "النبأ", englishName: "An-Naba", revelationType: "Meccan", versesCount: 40),
  Surah(number: 79, name: "النازعات", englishName: "An-Naziat", revelationType: "Meccan", versesCount: 46),
  Surah(number: 80, name: "عبس", englishName: "Abasa", revelationType: "Meccan", versesCount: 42),
  Surah(number: 81, name: "التكوير", englishName: "At-Takwir", revelationType: "Meccan", versesCount: 29),
  Surah(number: 82, name: "الإنفطار", englishName: "Al-Infitar", revelationType: "Meccan", versesCount: 19),
  Surah(number: 83, name: "المطففين", englishName: "Al-Mutaffifin", revelationType: "Meccan", versesCount: 36),
  Surah(number: 84, name: "الإنشقاق", englishName: "Al-Inshiqaq", revelationType: "Meccan", versesCount: 25),
  Surah(number: 85, name: "البروج", englishName: "Al-Buruj", revelationType: "Meccan", versesCount: 22),
  Surah(number: 86, name: "الطارق", englishName: "At-Tariq", revelationType: "Meccan", versesCount: 17),
  Surah(number: 87, name: "الأعلى", englishName: "Al-Ala", revelationType: "Meccan", versesCount: 19),
  Surah(number: 88, name: "الغاشية", englishName: "Al-Ghashiyah", revelationType: "Meccan", versesCount: 26),
  Surah(number: 89, name: "الفجر", englishName: "Al-Fajr", revelationType: "Meccan", versesCount: 30),
  Surah(number: 90, name: "البلد", englishName: "Al-Balad", revelationType: "Meccan", versesCount: 20),
  Surah(number: 91, name: "الشمس", englishName: "Ash-Shams", revelationType: "Meccan", versesCount: 15),
  Surah(number: 92, name: "الليل", englishName: "Al-Lail", revelationType: "Meccan", versesCount: 21),
  Surah(number: 93, name: "الضحى", englishName: "Ad-Duha", revelationType: "Meccan", versesCount: 11),
  Surah(number: 94, name: "الشرح", englishName: "Ash-Sharh", revelationType: "Meccan", versesCount: 8),
  Surah(number: 95, name: "التين", englishName: "At-Tin", revelationType: "Meccan", versesCount: 8),
  Surah(number: 96, name: "العلق", englishName: "Al-Alaq", revelationType: "Meccan", versesCount: 19),
  Surah(number: 97, name: "القدر", englishName: "Al-Qadr", revelationType: "Meccan", versesCount: 5),
  Surah(number: 98, name: "البينة", englishName: "Al-Bayinah", revelationType: "Medinan", versesCount: 8),
  Surah(number: 99, name: "الزلزلة", englishName: "Az-Zalzalah", revelationType: "Medinan", versesCount: 8),
  Surah(number: 100, name: "العاديات", englishName: "Al-Adiyat", revelationType: "Meccan", versesCount: 11),
  Surah(number: 101, name: "القارعة", englishName: "Al-Qariah", revelationType: "Meccan", versesCount: 11),
  Surah(number: 102, name: "التكاثر", englishName: "Al-Takathur", revelationType: "Meccan", versesCount: 8),
  Surah(number: 103, name: "العصر", englishName: "Al-Asr", revelationType: "Meccan", versesCount: 3),
  Surah(number: 104, name: "الهمزة", englishName: "Al-Humazah", revelationType: "Meccan", versesCount: 9),
  Surah(number: 105, name: "الفيل", englishName: "Al-Fil", revelationType: "Meccan", versesCount: 5),
  Surah(number: 106, name: "قريش", englishName: "Quraish", revelationType: "Meccan", versesCount: 4),
  Surah(number: 107, name: "الماعون", englishName: "Al-Ma'un", revelationType: "Meccan", versesCount: 7),
  Surah(number: 108, name: "الكوثر", englishName: "Al-Kauthar", revelationType: "Meccan", versesCount: 3),
  Surah(number: 109, name: "الكافرون", englishName: "Al-Kafirun", revelationType: "Meccan", versesCount: 6),
  Surah(number: 110, name: "النصر", englishName: "An-Nasr", revelationType: "Medinan", versesCount: 3),
  Surah(number: 111, name: "المسد", englishName: "Al-Masad", revelationType: "Meccan", versesCount: 5),
  Surah(number: 112, name: "الإخلاص", englishName: "Al-Ikhlas", revelationType: "Meccan", versesCount: 4),
  Surah(number: 113, name: "الفلق", englishName: "Al-Falaq", revelationType: "Meccan", versesCount: 5),
  Surah(number: 114, name: "الناس", englishName: "An-Nas", revelationType: "Meccan", versesCount: 6),
];
